"""Initial RTR-TradeScope schema with auth-ready nullable user ownership."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "0001_initial"; down_revision = None; branch_labels = None; depends_on = None
uuid = postgresql.UUID(as_uuid=True); money = sa.Numeric(20, 8); timestamps = lambda: [sa.Column("id", uuid, primary_key=True), sa.Column("user_id", uuid, nullable=True, index=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)]
def upgrade():
    op.create_table("strategies", *timestamps(), sa.Column("name", sa.String(150), nullable=False, unique=True), sa.Column("description", sa.Text, nullable=False, server_default=""), sa.Column("preferred_markets", sa.Text, nullable=False, server_default=""), sa.Column("preferred_session", sa.String(30), nullable=False), sa.Column("risk_rules", sa.Text, nullable=False, server_default=""), sa.Column("entry_rules", sa.Text, nullable=False, server_default=""), sa.Column("exit_rules", sa.Text, nullable=False, server_default=""), sa.Column("notes", sa.Text, nullable=False, server_default=""))
    op.create_table("trades", *timestamps(), sa.Column("symbol", sa.String(30), nullable=False, index=True), sa.Column("direction", sa.String(4), nullable=False), sa.Column("entry_price", money, nullable=False), sa.Column("stop_loss", money, nullable=False), sa.Column("take_profit", money), sa.Column("exit_price", money), sa.Column("position_size", money, nullable=False), sa.Column("trade_date", sa.Date, nullable=False), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.Column("session", sa.String(30), nullable=False), sa.Column("strategy_id", uuid, sa.ForeignKey("strategies.id", ondelete="SET NULL")), sa.Column("strategy_name", sa.String(150), nullable=False, server_default=""), sa.Column("status", sa.String(20), nullable=False), sa.Column("result", sa.String(20), nullable=False), sa.Column("notes", sa.Text, nullable=False, server_default=""), sa.Column("screenshot_url", sa.Text), sa.Column("risk", money, nullable=False), sa.Column("potential_reward", money, nullable=False), sa.Column("risk_reward_ratio", money, nullable=False), sa.Column("realized_r", money, nullable=False), sa.Column("pnl", money, nullable=False))
    op.create_table("alerts", *timestamps(), sa.Column("symbol", sa.String(30), nullable=False, index=True), sa.Column("target_price", money, nullable=False), sa.Column("condition", sa.String(10), nullable=False), sa.Column("note", sa.Text, nullable=False, server_default=""), sa.Column("status", sa.String(20), nullable=False), sa.Column("triggered_at", sa.DateTime(timezone=True)))
    for table in ("trades", "strategies", "alerts"): op.execute(f'ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY')
def downgrade():
    op.drop_table("alerts"); op.drop_table("trades"); op.drop_table("strategies")
