import { useEffect, useState } from "react";
import { RefreshCw, Server } from "lucide-react";
import { api } from "@/services/api";

interface Account { id: string; label: string; broker: string; login_masked: string; server: string; connection_type: string; status: string; currency: string | null; balance: string | null; equity: string | null; margin: string | null; free_margin: string | null; leverage: number | null; last_synced_at: string | null; last_error: string | null }
interface Position { id: string; symbol: string; direction: "BUY" | "SELL"; entry_price: string; current_price: string | null; volume: string; stop_loss: string | null; take_profit: string | null; floating_pnl: string | null; opened_at: string }
interface SyncRun { id: string; status: string; positions_received: number; deals_received: number; new_deals: number; cursor_ticket: number | null; message: string; created_at: string }

export function TradingAccountsSettings() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [positions, setPositions] = useState<Record<string, Position[]>>({}); const [runs, setRuns] = useState<Record<string, SyncRun[]>>({}); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ label: "", broker: "", login: "", server: "", connection_type: "WINDOWS_BRIDGE" });
  const load = async () => { try { setError(""); const items = await api.get<Account[]>("/api/trading-accounts"); setAccounts(items); const entries = await Promise.all(items.map(async (account) => [account.id, await api.get<Position[]>(`/api/trading-accounts/${account.id}/positions`), await api.get<SyncRun[]>(`/api/trading-accounts/${account.id}/sync-runs`)] as const)); setPositions(Object.fromEntries(entries.map(([id, values]) => [id, values]))); setRuns(Object.fromEntries(entries.map(([id, , values]) => [id, values]))); } catch (caught) { setError(caught instanceof Error ? caught.message : "Trading accounts unavailable"); } };
  useEffect(() => { void load(); }, []);
  const connect = async () => { if (!form.label || !form.broker || !form.login || !form.server) return; setSaving(true); try { await api.post<Account>("/api/trading-accounts", form); setForm({ ...form, login: "" }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Account metadata could not be saved"); } finally { setSaving(false); } };
  const money = (value: string | null, currency: string | null) => value === null ? "—" : new Intl.NumberFormat(undefined, { style: "currency", currency: currency || "USD" }).format(Number(value));
  return <section className="rounded-xl border border-[#263541] bg-[#121b23] p-5">
    <div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[13px] font-bold text-[#dce5e6]"><Server size={15} className="text-[#4ce0b1]" /> Trading Accounts</div><p className="mt-1 text-[10px] text-[#71818d]">Read-only MT5 metadata. Broker credentials remain on the Windows bridge host.</p></div><button onClick={() => void load()} aria-label="Refresh MT5 accounts" className="rounded border border-[#30404c] p-2 text-[#81929b]"><RefreshCw size={13}/></button></div>
    <div className="mt-4 grid gap-2 md:grid-cols-5"><input aria-label="Account label" placeholder="Personal Live" value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })}/><input aria-label="Broker" placeholder="JP Markets" value={form.broker} onChange={(event) => setForm({ ...form, broker: event.target.value })}/><input aria-label="MT5 login" inputMode="numeric" autoComplete="off" placeholder="MT5 account number" value={form.login} onChange={(event) => setForm({ ...form, login: event.target.value.replace(/\D/g, "") })}/><input aria-label="Broker server" placeholder="JPMarkets-Live" value={form.server} onChange={(event) => setForm({ ...form, server: event.target.value })}/><button disabled={saving || !form.label || !form.broker || form.login.length < 4 || !form.server} onClick={() => void connect()} className="rounded-lg bg-[#315e55] px-3 py-2 text-[10px] font-bold text-[#a2ead4] disabled:opacity-40">{saving ? "Saving…" : "Connect MT5 Account"}</button></div>
    <div className="mt-2 text-[9px] text-[#62737e]">Connection type: Windows MT5 Bridge. No password is collected or stored by RTR.</div>
    {error && <div role="alert" className="mt-3 rounded border border-[#6d4145] bg-[#2c2024] p-2 text-[10px] text-[#e59a92]">{error}</div>}
    <div className="mt-4 grid gap-3">{accounts.map((account) => <article key={account.id} className="rounded-lg border border-[#293943] bg-[#0e171e] p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[12px] font-bold text-[#d4dfe1]">{account.label}</div><div className="mt-1 text-[9px] text-[#778993]">{account.login_masked} · {account.broker} · {account.server}</div></div><div className={`text-[9px] font-bold ${account.status === "CONNECTED" ? "text-[#62d9b5]" : "text-[#df8a72]"}`}>● MT5 {account.status}</div></div><div className="mt-3 grid grid-cols-2 gap-2 text-[9px] text-[#82939d] md:grid-cols-5"><span>Balance<br/><b className="text-[#c3d0d3]">{money(account.balance, account.currency)}</b></span><span>Equity<br/><b className="text-[#c3d0d3]">{money(account.equity, account.currency)}</b></span><span>Free margin<br/><b className="text-[#c3d0d3]">{money(account.free_margin, account.currency)}</b></span><span>Open trades<br/><b className="text-[#c3d0d3]">{positions[account.id]?.length ?? 0}</b></span><span>Last sync<br/><b className="text-[#c3d0d3]">{account.last_synced_at ? new Date(account.last_synced_at).toLocaleString() : "Never"}</b></span></div>{account.last_error && <div className="mt-2 text-[9px] text-[#d38d84]">{account.last_error}</div>}{(positions[account.id]?.length ?? 0) > 0 && <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-[9px]"><thead className="text-[#60727d]"><tr><th>Symbol</th><th>Side</th><th>Entry</th><th>Volume</th><th>SL</th><th>TP</th><th>Floating P/L</th></tr></thead><tbody>{positions[account.id].map((position) => <tr key={position.id} className="border-t border-[#20303a] text-[#aab8bd]"><td>{position.symbol}</td><td>{position.direction}</td><td>{position.entry_price}</td><td>{position.volume}</td><td>{position.stop_loss ?? "—"}</td><td>{position.take_profit ?? "—"}</td><td>{position.floating_pnl ?? "—"}</td></tr>)}</tbody></table></div>}<div className="mt-3 border-t border-[#20303a] pt-2"><div className="text-[8px] font-bold uppercase tracking-[.14em] text-[#61737d]">Sync log</div>{runs[account.id]?.slice(0, 4).map((run) => <div key={run.id} className="mt-1 text-[8px] text-[#778993]">{new Date(run.created_at).toLocaleTimeString()} · {run.status} · {run.new_deals} new deals · {run.positions_received} positions</div>) ?? <div className="mt-1 text-[8px] text-[#61737d]">No sync runs yet.</div>}</div></article>)}</div>
  </section>;
}
